

services:
  api:
    build: .
    container_name: nistula_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://nistula_user:nistula_password@db:5432/nistula_db
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: nistula_db
    restart: always
    environment:
      POSTGRES_USER: nistula_user
      POSTGRES_PASSWORD: nistula_password
      POSTGRES_DB: nistula_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nistula_user -d nistula_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: